# Generated by Django 5.2.6 on 2025-10-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_financialprofile_current_savings_and_more'),
    ]

    operations = [
    ]
