# Generated by Django 5.2.6 on 2025-10-08 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_add_projection_scenarios"),
        ("api", "0004_auto_20251008_1439"),
    ]

    operations = []
