# Generated by Django 5.2.6 on 2025-10-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeentry',
            name='savings_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
