# Generated by Django 5.2.6 on 2025-10-29 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_incomeentry_savings_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_location', models.CharField(help_text='City, State, Country', max_length=200)),
                ('number_of_children', models.IntegerField(help_text='Desired number of children')),
                ('house_size_sqft', models.IntegerField(help_text='Desired house size in square feet')),
                ('house_type', models.CharField(choices=[('single_family', 'Single Family Home'), ('condo', 'Condo/Apartment'), ('townhouse', 'Townhouse'), ('multi_family', 'Multi-Family Home')], default='single_family', max_length=50)),
                ('estimated_home_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_monthly_mortgage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_property_tax_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_insurance_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_utilities_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_maintenance_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_childcare_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_education_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_child_healthcare_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_child_food_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_child_clothing_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_transportation_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_healthcare_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_groceries_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ai_response_raw', models.TextField(blank=True, help_text='Raw AI response for debugging')),
                ('ai_model_used', models.CharField(default='gpt-4', max_length=100)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score 0-1', max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
