# Generated by Django 5.2.6 on 2025-10-29 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_aicostestimate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='City, State, Country', max_length=200)),
                ('start_year', models.IntegerField(help_text='Starting year for this location')),
                ('end_year', models.IntegerField(help_text='Ending year for this location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_year'],
            },
        ),
        migrations.CreateModel(
            name='SpendingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_spending', models.CharField(choices=[('very_little', 'Very Little'), ('less_than_average', 'Less Than Average'), ('average', 'Average'), ('above_average', 'Above Average'), ('very_high', 'Very High')], default='average', max_length=20)),
                ('travel_spending', models.CharField(choices=[('very_little', 'Very Little'), ('less_than_average', 'Less Than Average'), ('average', 'Average'), ('above_average', 'Above Average'), ('very_high', 'Very High')], default='average', max_length=20)),
                ('food_spending', models.CharField(choices=[('very_little', 'Very Little'), ('less_than_average', 'Less Than Average'), ('average', 'Average'), ('above_average', 'Above Average'), ('very_high', 'Very High')], default='average', max_length=20)),
                ('leisure_spending', models.CharField(choices=[('very_little', 'Very Little'), ('less_than_average', 'Less Than Average'), ('average', 'Average'), ('above_average', 'Above Average'), ('very_high', 'Very High')], default='average', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
