# Generated by Django 5.2.6 on 2025-10-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_locationpreference_spendingpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeentry',
            name='costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual costs/expenses', max_digits=12, null=True),
        ),
    ]
