# Generated by Django 5.2.6 on 2025-10-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_incomeentry_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeentry',
            name='location',
            field=models.CharField(blank=True, help_text='Location for this year', max_length=200, null=True),
        ),
    ]
