# Generated by Django 5.2.6 on 2025-10-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_incomeentry_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeentry',
            name='after_tax_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Income after taxes', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='federal_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Federal income tax', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='state_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='State income tax', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='total_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total income tax (federal + state)', max_digits=12, null=True),
        ),
    ]
