# Generated by Django 5.2.6 on 2025-11-03 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_incomeentry_after_tax_income_incomeentry_federal_tax_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonteCarloSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_iterations', models.IntegerField(help_text='Number of Monte Carlo iterations run')),
                ('projected_years', models.IntegerField(help_text='Number of years projected')),
                ('base_return_rate', models.DecimalField(decimal_places=2, help_text='Expected annual return rate', max_digits=5)),
                ('return_rate_std_dev', models.DecimalField(decimal_places=2, help_text='Standard deviation of annual returns', max_digits=5)),
                ('base_inflation_rate', models.DecimalField(decimal_places=2, help_text='Expected inflation rate', max_digits=5)),
                ('inflation_rate_std_dev', models.DecimalField(decimal_places=2, help_text='Standard deviation of inflation rate', max_digits=5)),
                ('mean_final_value', models.DecimalField(decimal_places=2, help_text='Mean of all iterations', max_digits=12)),
                ('median_final_value', models.DecimalField(decimal_places=2, help_text='Median of all iterations', max_digits=12)),
                ('std_dev_final_value', models.DecimalField(decimal_places=2, help_text='Standard deviation', max_digits=12)),
                ('min_final_value', models.DecimalField(decimal_places=2, help_text='Minimum final value', max_digits=12)),
                ('max_final_value', models.DecimalField(decimal_places=2, help_text='Maximum final value', max_digits=12)),
                ('percentile_5', models.DecimalField(decimal_places=2, help_text='5th percentile (worst case)', max_digits=12)),
                ('percentile_25', models.DecimalField(decimal_places=2, help_text='25th percentile', max_digits=12)),
                ('percentile_75', models.DecimalField(decimal_places=2, help_text='75th percentile', max_digits=12)),
                ('percentile_95', models.DecimalField(decimal_places=2, help_text='95th percentile (best case)', max_digits=12)),
                ('success_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of iterations that met goal (if goal set)', max_digits=5, null=True)),
                ('target_goal', models.DecimalField(blank=True, decimal_places=2, help_text='Target goal amount (optional)', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projectionscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonteCarloIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_number', models.IntegerField(help_text='Iteration number (1-indexed)')),
                ('final_value', models.DecimalField(decimal_places=2, help_text='Final portfolio value', max_digits=12)),
                ('total_contributions', models.DecimalField(decimal_places=2, help_text='Total contributions made', max_digits=12)),
                ('total_gains', models.DecimalField(decimal_places=2, help_text='Total gains earned', max_digits=12)),
                ('avg_return_rate', models.DecimalField(decimal_places=2, help_text='Average return rate used', max_digits=5)),
                ('avg_inflation_rate', models.DecimalField(decimal_places=2, help_text='Average inflation rate used', max_digits=5)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='api.montecarlosimulation')),
            ],
            options={
                'ordering': ['iteration_number'],
                'unique_together': {('simulation', 'iteration_number')},
            },
        ),
    ]
