# Generated by Django 5.2.6 on 2025-11-23 20:27

from django.db import migrations, models


def convert_spending_preferences_to_percentages(apps, schema_editor):
    """Convert old text choices to percentage values"""
    SpendingPreference = apps.get_model('api', 'SpendingPreference')
    
    # Mapping from old text choices to percentage values
    # These are approximate conversions based on typical spending patterns
    choice_to_percentage = {
        'very_little': 10.0,
        'less_than_average': 20.0,
        'average': 30.0,
        'above_average': 40.0,
        'very_high': 50.0,
    }
    
    # Default percentages for each category
    default_percentages = {
        'housing_spending': 30.0,
        'travel_spending': 10.0,
        'food_spending': 15.0,
        'leisure_spending': 10.0,
    }
    
    for pref in SpendingPreference.objects.all():
        # Convert housing_spending
        old_value = pref.housing_spending
        if isinstance(old_value, str):
            pref.housing_spending_new = choice_to_percentage.get(
                old_value, default_percentages['housing_spending']
            )
        else:
            pref.housing_spending_new = default_percentages['housing_spending']
        
        # Convert travel_spending
        old_value = pref.travel_spending
        if isinstance(old_value, str):
            pref.travel_spending_new = choice_to_percentage.get(
                old_value, default_percentages['travel_spending']
            )
        else:
            pref.travel_spending_new = default_percentages['travel_spending']
        
        # Convert food_spending
        old_value = pref.food_spending
        if isinstance(old_value, str):
            pref.food_spending_new = choice_to_percentage.get(
                old_value, default_percentages['food_spending']
            )
        else:
            pref.food_spending_new = default_percentages['food_spending']
        
        # Convert leisure_spending
        old_value = pref.leisure_spending
        if isinstance(old_value, str):
            pref.leisure_spending_new = choice_to_percentage.get(
                old_value, default_percentages['leisure_spending']
            )
        else:
            pref.leisure_spending_new = default_percentages['leisure_spending']
        
        pref.save()


def reverse_conversion(apps, schema_editor):
    """Reverse conversion - convert percentages back to text choices"""
    # This is a one-way migration for now
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_montecarlosimulation_montecarloiteration'),
    ]

    operations = [
        # First, add new DecimalField columns (temporarily nullable)
        migrations.AddField(
            model_name='spendingpreference',
            name='housing_spending_new',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Percentage of income spent on housing (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='spendingpreference',
            name='travel_spending_new',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of income spent on travel (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='spendingpreference',
            name='food_spending_new',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Percentage of income spent on food (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='spendingpreference',
            name='leisure_spending_new',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of income spent on leisure (0-100)', max_digits=5, null=True),
        ),
        # Convert data
        migrations.RunPython(convert_spending_preferences_to_percentages, reverse_conversion),
        # Remove old fields
        migrations.RemoveField(
            model_name='spendingpreference',
            name='housing_spending',
        ),
        migrations.RemoveField(
            model_name='spendingpreference',
            name='travel_spending',
        ),
        migrations.RemoveField(
            model_name='spendingpreference',
            name='food_spending',
        ),
        migrations.RemoveField(
            model_name='spendingpreference',
            name='leisure_spending',
        ),
        # Rename new fields to original names
        migrations.RenameField(
            model_name='spendingpreference',
            old_name='housing_spending_new',
            new_name='housing_spending',
        ),
        migrations.RenameField(
            model_name='spendingpreference',
            old_name='travel_spending_new',
            new_name='travel_spending',
        ),
        migrations.RenameField(
            model_name='spendingpreference',
            old_name='food_spending_new',
            new_name='food_spending',
        ),
        migrations.RenameField(
            model_name='spendingpreference',
            old_name='leisure_spending_new',
            new_name='leisure_spending',
        ),
    ]
